# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0485ae40953952f6b5776e913c79a43cf34db00845a88008b67418150fdbb826e4edbbf1d7be6f40cb412474a0ed0030399cf5df99f557fa3355dfd47b77c412

test:
  secret_key_base: d2fcd5c2868f136e2aee3cd161224f8df52a11f8baf5aac34aecd9a39da5a219ce7ec3052b71223e6b7f7742609be4b56151c9e8aff9f821fc21328801737a2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
